loading in DATAFRAME

In [ ]:
import pandas as pd

In [14]:
coffee = pd.read_csv('./warmup-data/coffee.csv')

In [ ]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [17]:
olympicdata = pd.read_excel('./data/olympics-data.xlsx')

In [ ]:
coffee.iloc[:]

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [35]:
coffee.sort_values(["Coffee Type"])

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
1      Monday       Latte          15
3     Tuesday       Latte          20
5   Wednesday       Latte          25
7    Thursday       Latte          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35

In [36]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [37]:
bios = pd.read_csv('./data/bios.csv')

In [38]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [64]:
bios[bios['name'].str.contains('rumb',case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
7512,7553,Raymond Van Rumbeke,1908-10-13,Gy,Haute-Saône,FRA,Belgium,NaN,NaN,NaN
12597,12666,John Rumble,1933-08-27,Toronto,Ontario,CAN,Canada,NaN,NaN,2023-12-05
25560,25752,Gyula Rumbold,1887-12-06,Budapest,Budapest,HUN,Hungary,NaN,NaN,1959-10-05
40870,41181,Terry Rumbel,1951-07-24,NaN,NaN,NaN,Australia,185.0,100.0,NaN
54669,55063,Ivo Trumbić,1935-04-02,Split,Splitsko-dalmatinska županija,CRO,Yugoslavia,197.0,103.0,2021-03-12
74637,75210,Cornel Porumb,1939-05-11,Sibiu,Sibiu,ROU,Romania,190.0,75.0,2007-01-01
93981,94740,Raema Lisa Rumbewas,1980-10-10,Jayapura,Papua,INA,Indonesia,149.0,53.0,NaN
96221,96997,Alberts Rumba,1892-10-15,Lielvircava,Jelgavas novads,LAT,Latvia,NaN,NaN,1962-07-10
99093,99889,Courtney Rumbolt,1969-07-26,London,England,GBR,Great Britain,185.0,104.0,NaN
100873,101736,Elmira Urumbayeva,1973-10-03,Bustanlik,Toshkent Viloyati,UZB,Uzbekistan,NaN,NaN,NaN
116584,117980,Jane Rumball,1978-07-09,Fredericton,New Brunswick,CAN,Canada,178.0,65.0,NaN
121677,123691,Arnis Rumbenieks,1988-04-04,Valmiera,Valmiera,LAT,Latvia,175.0,63.0,NaN
139130,142580,Marc Larumbe,1994-05-30,Barcelona,Barcelona,ESP,Spain,193.0,93.0,NaN
143128,146760,David Rumbutis,2000-03-17,Älvsbyn,Norrbotten,SWE,Sweden,NaN,NaN,NaN